name: GummyMC
version: '${project.version}'
main: me.wizzo.gummymc.GummyMC
authors: [ wizzo ]
description: The main system of GummyMC
softdepend:
  - PlaceholderAPI

commands:
  message:
    description: send a private message to player
    aliases:
      - msg
      - pmessage
  reply:
    description: use for response to a private message
    aliases:
      - r
  gm:
    description: modify your gamemode
    aliases:
      - gamemode
  vanish:
    description: enable or disable vanish mode
    aliases:
      - v
  fly:
    description: enable or disable fly
  teleport:
    description: teleport you or a player on another player
    aliases:
      - tp
  teleportall:
    description: teleport all players online to you or antoher player
    aliases:
      - tpall
  invsee:
    description: open a player's inventory
    aliases:
      - seeinv
      - seeinventory
      - openinv
  ping:
    description: see your or another player's ping
    aliases:
      - latency
      - ms
  mention:
    description: enable or disable your mentions
    aliases:
      - menzione
  god:
    description: enable or disable god mode
    aliases:
      - gesu
      - dio
  warp:
    description: warp system command
    aliases:
      - home
  warps:
    description: alias for warp list command
    aliases:
      - homes